#!/usr/bin/env python3
"""
Alluvium — Standalone Note Intake

Folds hand-written standalone notes (e.g. a substantial concept note dropped in
01 Inbox/) into the vault *in parallel to the daily journal*, without dismantling
them. The note's prose is kept whole; the pipeline only adds metadata: it
classifies the note into the right PARA folder, fills in domain/type/tags, threads
it to the day via source_entries, and hands it to the ripple engine so it compounds
into the rest of the vault.

A note is a "standalone source" for a given day when it lives in 01 Inbox/, was
written that day, and was NOT generated by the pipeline. Pipeline-generated atoms
always carry a `source_entries` frontmatter field, so their absence is the
discriminator; a `alluvium_processed` sentinel prevents re-folding on later runs.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

from llm import call_llm_json
from process_journal import load_config

# --- Paths ---
BASE_DIR = Path(__file__).parent
INBOX_DIR = BASE_DIR / "01 Inbox"
PEOPLE_DIR = BASE_DIR / "People"

PARA_FOLDERS = {
    "project": BASE_DIR / "1 Projects",
    "area": BASE_DIR / "2 Areas",
    "resource": BASE_DIR / "3 Resources",
    "archive": BASE_DIR / "4 Archive",
}

# Canonical frontmatter key order (unknown user keys are preserved after these).
_FM_ORDER = [
    "title", "aliases", "date_created", "date_modified", "type", "domain",
    "para", "tags", "source_entries", "related", "status", "alluvium_processed",
]


def _parse_note(path: Path) -> tuple[dict, str]:
    """Return (frontmatter dict, body) for a note. Missing/invalid frontmatter -> {}."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            try:
                fm = yaml.safe_load(parts[1]) or {}
            except Exception:
                fm = {}
            return (fm if isinstance(fm, dict) else {}), parts[2].lstrip("\n")
    return {}, text


def _note_date(path: Path, fm: dict) -> date | None:
    """Effective date of a note: frontmatter date if present, else file mtime."""
    for key in ("date_created", "date_modified"):
        raw = fm.get(key)
        if raw:
            try:
                return date.fromisoformat(str(raw)[:10])
            except ValueError:
                pass
    try:
        from datetime import datetime
        return datetime.fromtimestamp(path.stat().st_mtime).date()
    except OSError:
        return None


def _first_heading(body: str) -> str | None:
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return None


def find_standalone_notes(target_date: date) -> list[Path]:
    """Inbox notes written on target_date that the pipeline has not generated/folded."""
    if not INBOX_DIR.exists():
        return []
    found = []
    for f in INBOX_DIR.rglob("*.md"):
        if f.name.startswith("_"):
            continue
        fm, _ = _parse_note(f)
        # Pipeline atoms carry source_entries; folded notes carry alluvium_processed.
        if fm.get("source_entries") or fm.get("alluvium_processed"):
            continue
        if _note_date(f, fm) == target_date:
            found.append(f)
    return found


def _build_classify_prompt(title: str, body: str, config: dict, para_enabled: bool) -> str:
    domains_desc = "\n".join(
        f"- **{key}**: {d['description']}" for key, d in config["domains"].items()
    )
    domain_keys = ", ".join(config["domains"].keys()) + ", personal"
    note_types = ", ".join(config["note_types"])

    para_rules = para_field = ""
    if para_enabled:
        para_rules = (
            "\nPARA categories: project (active effort with a deadline), area "
            "(ongoing responsibility), resource (reference material / an idea worth "
            "keeping), archive (finished or inactive)."
        )
        para_field = '\n- "para": one of project|area|resource|archive'

    return f"""You are classifying a standalone note for a personal knowledge system. Read the note and assign metadata. Do NOT rewrite, summarize, or alter the note's text — only classify it.

## Life domains
{domains_desc}
{para_rules}

## Note title
{title}

## Note content
{body[:6000]}

## Output
Return ONLY a JSON object (no commentary, no code fences):
- "domain": one of {domain_keys}
- "type": one of {note_types}
- "tags": list of 3-8 lowercase, hyphenated tags emergent from the content{para_field}
"""


def _classify(title: str, body: str, config: dict, para_enabled: bool) -> dict:
    """Ask the LLM for metadata, then normalise it against the config taxonomy."""
    result = call_llm_json(_build_classify_prompt(title, body, config, para_enabled), max_tokens=1024)
    if not isinstance(result, dict):
        result = {}

    domain_keys = set(config["domains"].keys()) | {"personal"}
    domain = result.get("domain")
    if domain not in domain_keys:
        domain = "personal"

    note_types = set(config["note_types"])
    ntype = result.get("type")
    if ntype not in note_types:
        ntype = "reflection"

    tags = [str(t).lower().strip() for t in result.get("tags", []) if str(t).strip()]

    para = result.get("para")
    if para not in PARA_FOLDERS:
        para = None

    return {"domain": domain, "type": ntype, "tags": tags, "para": para}


def _destination(stem: str, note_type: str, para: str | None, para_enabled: bool) -> Path:
    if note_type == "person":
        return PEOPLE_DIR / f"{stem}.md"
    if para_enabled and para in PARA_FOLDERS:
        return PARA_FOLDERS[para] / f"{stem}.md"
    return INBOX_DIR / f"{stem}.md"


def _fold_in(path: Path, target_date: str, config: dict, existing_notes: dict, para_enabled: bool) -> str | None:
    fm, body = _parse_note(path)
    title = fm.get("title") or _first_heading(body) or path.stem.replace("-", " ")

    cls = _classify(title, body, config, para_enabled)

    # Preserve the user's note and any custom frontmatter keys; only set/override
    # the Alluvium-managed fields.
    new_fm = dict(fm)
    new_fm["title"] = title
    new_fm["aliases"] = fm.get("aliases", [])
    new_fm["date_created"] = fm.get("date_created") or target_date
    new_fm["date_modified"] = target_date
    new_fm["type"] = cls["type"]
    new_fm["domain"] = cls["domain"]
    if para_enabled and cls["para"]:
        new_fm["para"] = cls["para"]
    new_fm["tags"] = sorted(set(fm.get("tags", []) or []) | set(cls["tags"]))
    new_fm["source_entries"] = [f"[[{target_date}]]"]  # threads the note to the day
    new_fm["related"] = fm.get("related", [])
    new_fm["status"] = fm.get("status", "active")
    new_fm["alluvium_processed"] = target_date  # sentinel: never re-fold

    ordered = {k: new_fm[k] for k in _FM_ORDER if k in new_fm}
    ordered.update({k: v for k, v in new_fm.items() if k not in ordered})

    content = "---\n"
    content += yaml.dump(ordered, default_flow_style=False, allow_unicode=True, sort_keys=False)
    content += "---\n\n"
    content += body.rstrip("\n") + "\n"
    path.write_text(content, encoding="utf-8")

    # Route into the right folder (mirrors write_note's placement logic).
    dest = _destination(path.stem, cls["type"], cls["para"], para_enabled)
    if dest != path:
        if dest.exists():
            print(f"  [keep]  {path.name} — '{dest.parent.name}/{dest.name}' already exists, left in Inbox")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            path.rename(dest)
            path = dest
            print(f"  [fold]  {dest.name} → {dest.parent.name}/")
    else:
        print(f"  [fold]  {path.name}")

    existing_notes[path.stem] = path
    return title


def process_standalone_notes(target_date: date, existing_notes: dict, para_enabled: bool = True, config: dict | None = None) -> list[str]:
    """Fold all of target_date's standalone Inbox notes into the vault.

    Returns the titles of the notes folded in (for journal backlinks + ripple).
    Each note is handled independently; a failure on one is non-fatal.
    """
    candidates = find_standalone_notes(target_date)
    if not candidates:
        return []

    config = config or load_config()
    date_str = target_date.isoformat()
    print(f"\nFolding in {len(candidates)} standalone note(s) from {date_str}:")

    titles = []
    for f in candidates:
        try:
            title = _fold_in(f, date_str, config, existing_notes, para_enabled)
            if title:
                titles.append(title)
        except Exception as e:
            print(f"  ⚠ Could not fold in {f.name} (non-fatal): {e}")
    return titles
